# See wiki for documentation: https://github.com/40Cakes/pokebot-gen3/tree/main/wiki/pages/Configuration%20-%20Logging%20and%20Console%20Output.md

# Log all encounters to .csv (`stats/encounters/` folder), each phase is logged to a separate file
log_encounters: false # `true`, `false`

# Console output
# `verbose`, `basic`, `disable`
console:
  encounter_data: verbose
  encounter_ivs: verbose
  encounter_moves: disable
  statistics: verbose

# Save .pk3 files
save_pk3:
  all: false
  shiny: true
  custom: true

# Automatically load .pk3 file into PC storage
import_pk3: false
