# Toggle battling all other wild Pokémon
# Catching shinies and Pokémon in CustomCatchFilters.py always takes priority over battling
# Valid options: `true`, `false`
battle: true

# Enable pickup - https://bulbapedia.bulbagarden.net/wiki/Pickup_(Ability)#Generations_III_and_IV
# Valid options: `true`, `false`
pickup: true

# Threshold of party members with items before collecting the items from them
# Valid option: (integer 1-6)
pickup_threshold: 3

# How many encounters should take place before checking for a pickup item
# Valid option: (positive integer)
pickup_check_frequency: 5

# What to do if the lead Pokémon faints.
# Valid option: `stop`, `flee`, `rotate`
faint_action: rotate

# Toggle handling of new move learning
# If stop is selected, the bot will exit and let you control. If cancel is selected, all new moves will
# not be learned. This will also cancel any evolutions that happen during run time.
# Valid options: `stop`, `cancel`, 'learn_best'
new_move: learn_best

# Toggle evolution canceling
# Set true if you do not want your Pokémon to evolve
# Valid options: `true`, `false`
stop_evolution: false

# Toggle battler rotation
# If true, the bot will replace the lead battler when the lead battler's health drops below 20% or the lead battler has
# no effective moves.
# Valid options: `true`, `false`
replace_lead_battler: true

# Rotation strategy:
# If set to `first_available`, the bot will switch to the first Pokémon that has more than 20% hp and at least 1 pp of a
# damaging move. Future support will be added for a smarter switching option that takes into account how much damage the
# switch in will take, and how much damage the switch in can do.
# Valid options: `first_available`
switch_strategy: first_available

# Battle method:
# If set to strongest, bot will choose the most powerful move to use against the current foe. Future support to battle
# more intelligently is planned.
# Valid options: `strongest`
battle_method: strongest

# Banned moves
# Any moves in this list will not be used in battle
banned_moves:
- None
  # 2-turn
- Bounce
- Dig
- Dive
- Fly
- Sky Attack
- Razor Wind
- Doom Desire
- Solar Beam
  # Inconsistent
- Fake Out
- False Swipe
- Nature Power
- Present
- Destiny Bond
- Wrap
- Snore
- Spit Up
- Bide
- Bind
- Counter
- Future Sight
- Mirror Coat
- Grudge
- Snatch
- Spite
- Curse
- Endeavor
- Revenge
- Assist
- Focus Punch
- Eruption
- Flail
  # Ends battle
- Roar
- Whirlwind
- Selfdestruct
- Perish Song
- Explosion
- Memento
