# Cheats config
# See readme for documentation

starters: false # `true`, `false`

# -----------------------------------------
# Everything below is not implemented, yet™
# -----------------------------------------

# TODO RNG manipulation
# TODO egg resets
# TODO instant find Feebas tile
# TODO instant find roamer map
