# Cheats
# Perform "cheaty" actions such as peeking into eggs to check shininess, knowing instantly which route a roamer is on,
# instantly locate Feebas tiles etc.

# Starters - enabling this will soft reset a few frames after generating the starter Pokémon, bypassing throwing
# the Pokémon out into battle animation, saving a bit of time
# Valid options: `true`, `false`
# TODO not implemented
starters: false

# TODO RNG manipulation
# TODO egg resets
# TODO instant find Feebas tile
# TODO instant find roamer map
