# Cheats config
# See readme for documentation: https://github.com/40Cakes/pokebot-gen3#-configuration

starters: false # `true`, `false`
starters_rng: false # `true`, `false`

# -----------------------------------------
# Everything below is not implemented, yet™
# -----------------------------------------

# TODO RNG manipulation
# TODO egg resets
# TODO instant find Feebas tile
# TODO instant find roamer map
