# Discord settings
# See readme for documentation

rich_presence: true # `true`, `false`
webhooks: true # `true`, `false`
global_webhook_url: https://discord.com/api/webhooks/<your_webhook_here>
iv_format: formatted # `basic`, `formatted`
bot_id: PokéBot # Any string of text

# Shiny Pokémon encounters
shiny_pokemon_encounter:
  enable: true
  ping_mode:
  ping_id:
  #webhook_url:

# Pokémon encounter milestones
pokemon_encounter_milestones:
  enable: true
  interval: 10000
  ping_mode:
  ping_id:
  #webhook_url:

# Shiny Pokémon encounter milestones
shiny_pokemon_encounter_milestones:
  enable: true
  interval: 5
  ping_mode:
  ping_id:
  #webhook_url:

# Total encounter milestones
total_encounter_milestones:
  enable: true
  interval: 25000
  ping_mode:
  ping_id:
  #webhook_url:

# Phase summary
phase_summary:
  enable: true
  first_interval: 8192
  consequent_interval: 5000
  ping_mode:
  ping_id:
  #webhook_url:

# Anti-Shiny Pokémon encounters
anti_shiny_pokemon_encounter:
  enable: true
  ping_mode:
  ping_id:
  #webhook_url:
