# General settings
# See readme for documentation: https://github.com/40Cakes/pokebot-gen3#generalyml---general-config

# Bot mode
# `manual`, `spin`, `starters`, `fishing`
bot_mode: manual

# Starter - used when `bot_mode` is set to `starters`
# `Treecko`, `Torchic`, `Mudkip`, `Bulbasaur`, `Charmander`, `Squirtle`, `Chikorita`, `Cyndaquil`, `Totodile`
starter: Mudkip

# -----------------------------------------
# Everything below is not implemented, yet™
# -----------------------------------------

# Coords config - used when `bot_mode` is set to `coords`
# TODO not implemented
coords:
  pos1:
    x: 0
    y: 0
  pos2:
    x: 0
    y: 0

# Bonk direction - this config is used if `bot_mode` is set to `bonk`
# Bonk mode will run left/right or up/down repeatedly until the trainer bonks a wall
# TODO not implemented
bonk_direction: horizontal # `horizontal`, `vertical`

# Fossils - this config is used if `bot_mode` is set to `fossil`
# Save with trainer facing the Fossil Scientist in Devon after handing over the fossil and re-entering the room
# TODO not implemented
fossil: anorith # `anorith`, `lileep`

# Autosaves
# Autosave every n encounters, set to `0` to disable
# TODO not implemented
autosave_encounters: 1000

# Auto catch
# (if disabled the bot will pause and wait for you to manually catch)
# TODO not implemented
auto_catch: true # `true`, `false`

# Enable party leader to use Spore to sleep the wild Pokémon
# TODO not implemented
use_spore: true # `true`, `false`

# Toggle catching shinies on/off
# CustomCatchFilters.py allows you to configure filters to catch specific non-shiny Pokémon
# TODO not implemented
catch_shinies: true # `true`, `false`

# Set true if the Deoxys puzzle is solved already and the last save is on the tile in front of the red triangle
# TODO not implemented
deoxys_puzzle_solved: false # `true`, `false`

# Toggle auto stop when you are run out of balls
# Otherwise, if you want to continue without balls, this option needs to be false
# TODO not implemented
auto_stop: true # `true`, `false`

# Save the game after catch
# TODO not implemented
save_game_after_catch: true # `true`, `false`

# Pokeball overrides to catch certain Pokémon with specific balls
# Balls at the top of the list are highest priority, bottom is least priority
# The bot will fall back to `pokeball_priority` option if you have no balls specified in the list
# Examples are provided below (make sure to uncomment), note: `ball_override` is not validated by the config schema
# Exact Pokémon name + `Dive Ball`, `Great Ball`, `Luxury Ball`, `Master Ball`,
# `Nest Ball`, `Poké Ball`, `Premier Ball`, `Repeat Ball`, `Timer Ball`, `Ultra Ball`
# TODO not implemented
ball_override:
#  Abra:
#    - Ultra Ball
#    - Great Ball
#  Seedot:
#    - Master Ball

# Ball preferences (if no ball overrides are specified above)
# Top of the list is highest priority, bottom is least priority
# Valid options: `Dive Ball`, `Great Ball`, `Luxury Ball`, `Master Ball`, `Nest Ball`, `Poké Ball`, `Premier Ball`,
# `Repeat Ball`, `Timer Ball`, `Ultra Ball`
# TODO not implemented
ball_priority:
  - Ultra Ball
  - Great Ball
  - Premier Ball
  - Poké Ball
