# Logging/console output options
# See readme for documentation

# Log encounters to .csv files
log_encounters: true # `true`, `false`

# Console output
# `verbose`, `basic`, `disable`
console:
  encounter_data: verbose
  encounter_ivs: verbose
  encounter_moves: disable
  statistics: verbose

# Backups
backup_stats: 25000
