# Log Pokémon encounters to .csv files (logs to `stats/encounters/` folder)
# Valid options: `true`, `false`
log_encounters: true

# Console output
# Verbose options will provide stats in a formatted table, basic options will give a condensed, single line output
# Valid options: `verbose`, `basic`, `disable`
console:
  encounter_data: verbose
  encounter_ivs: verbose
  encounter_moves: disable
  statistics: verbose

# Backups
# Backup PokéBot stats/ folder every n encounters
# HIGHLY recommended to backup stats/ folder regularly, totals.json is known to get corrupted during power outages
# Make sure you regularly delete old backups (especially if your stats folder is large!)
# Set to 0 to disable
backup_stats: 25000
