# OBS settings
# See readme for documentation

shiny_delay: 0
discord_delay: 0
screenshot: false # `true`, `false`
replay_buffer: false # `true`, `false`
replay_buffer_delay: 0
hotkey_screenshot: ["ctrl", "f11"]
hotkey_replay_buffer: ["ctrl", "f12"]
replay_dir: "./stream/replays/"
webhook_url:

# Web server
server:
  enable: false # `true`, `false`
  ip: 127.0.0.1
  port: 8888
