# OBS settings
# See readme for documentation: https://github.com/40Cakes/pokebot-gen3#obsyml---obs-config

obs_websocket:
  host: 127.0.0.1
  port: 4455
  password: password

shiny_delay: 0
discord_delay: 0
screenshot: false # `true`, `false`
replay_buffer: false # `true`, `false`
replay_buffer_delay: 0
discord_webhook_url:
replay_dir: "./stream/replays/"

# Web server
http_server:
  enable: true # `true`, `false`
  ip: 127.0.0.1
  port: 8888
