# See wiki for documentation: https://github.com/40Cakes/pokebot-gen3/tree/main/wiki/pages/Console,%20Logging%20and%20Image%20Config.md

# Log all encounters to .csv (`stats/encounters/` folder), each phase is logged to a separate file
log_encounters: false # `true`, `false`

# Show a desktop notification if a shiny, roamer, or Pokémon matching your
# Custom Catch Filters is encountered, or the bot is switched to manual
# mode.
desktop_notifications: true

# Console output
# `verbose`, `basic`, `disable`
console:
  encounter_data: verbose
  encounter_ivs: verbose
  encounter_moves: disable
  statistics: verbose

# Save .pk3 files
save_pk3:
  all: false
  shiny: true
  custom: true
  roamer: true

# Save shiny GIFs
shiny_gifs: true

# Generate TCG cards
tcg_cards: true
